---
- hosts: localhost
  connection: local
  gather_facts: False

  remote_user: root
  tasks:
  - name: create rabbitmq dir
    file:
      path: /opt/rabbitmq
      state: directory
      mode: '0755'
  - name: download erlang rpm
    get_url:
      url: https://github.com/rabbitmq/erlang-rpm/releases/download/v22.2.4/erlang-22.2.4-1.el7.x86_64.rpm
      dest: /opt/rabbitmq/erlang-22.2.4-1.el7.x86_64.rpm
  - name: install  erlang
    yum:
      name: /opt/rabbitmq/erlang-22.2.4-1.el7.x86_64.rpm
      state: present
  - name: download server rpm
    get_url:
      url: https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.2/rabbitmq-server-3.8.2-1.el7.noarch.rpm
      dest: /opt/rabbitmq/rabbitmq-server-3.8.2-1.el7.noarch.rpm
  - name: "install server"
    yum:
      name: /opt/rabbitmq/rabbitmq-server-3.8.2-1.el7.noarch.rpm
      state: present
  - name: "start server "
    systemd:
      name: rabbitmq-server.service
      state: started
      enabled: yes
  - name: "start webui"
    shell: rabbitmq-plugins enable rabbitmq_management